<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="DatabaseClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="[99x].Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NameContactNoInvoice" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PostOffice" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telefax" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="WareHouseNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FormProfileCustNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FixedAddnDedNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TermsOfDeliveryNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeliveryMethodsNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PostCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="SortName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BuContactNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BusinessNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChainNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerProfileNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeeNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TermsOfPayCustNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerGrpNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DistrictNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PriceCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CurrencyNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreditLimit" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GLAccountRec" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContactNoInvoice" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountryNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FactCustomerNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CompanyNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PostAccount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BankAccount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastMovementDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GrossInvoicingYesNo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="DiscountGrpCustNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LockedYesNo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="OurSupplNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegistrationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CustomerTypeNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InActiveYesNo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ContactNoDelivery" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccessLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ChainLeaderYesNo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TypeOfChain" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProjectNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupplierNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeliveryAddressNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RoundingCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WWWAddress" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DebtCollectionGrpNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PriceListNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UtilityBits" Type="System.Data.Linq.Binary" DbType="Binary(6)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ExtraCostUnitIVNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExtraCostUnitIIINo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExtraCostUnitIINo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExtraCostUnitINo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastUpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EANLocationNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CustomerBonusProfileNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocalGovernmentNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChartererCompanyNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AgentNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CommissionProfileNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastSubscriptionInvoiceDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SubscriptionProfileNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoOfSubscription" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="RemittanceProfileNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AutogiroAgreementID" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="AgentYesNo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EbusinessType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShipmentTypeNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InvoiceName2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InvoiceName1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ExtraName1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RemainderOrderYesNo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="AcceptReplacementArticleYesNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NotBreakageYesNo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PrintProfileNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AverageCreditPeriod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PaymentPattern" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpperAmountAltPriceList" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AltPriceListYesNo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="AltPriceListNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MergeToCustomerNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContactNoListOfContents" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContactNoReminder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InvoiceAdressNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AgreementGiroType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EdiProfileNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EinvoiceStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EinvoiceRef" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AgreementOrderCusGrpNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SpecialEDIid" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="EDISellerRefNo" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="EDIBuyerRefNo" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="VATRegNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChainPriceTypeHasPriorityYesNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ZpiderImportProfileNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EdiTestYesNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDITestMode" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="WebshopRefNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GLAccountRecAlfa" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CreditControlLastAction" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreditControlLastActionTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreditControlLastActionOnName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZUsrTekstfelt" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ZUsrTekst2" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ZUsrTekst3" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ZUsrTekst4" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ZUsrKampanje" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="ZUsrKampanjeII" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ZUsrKampanjeIII" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ElectronicInvoiceActive" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ElectronicInvoiceOperator" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ElectronicInvoiceAddress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ElectronicInvoiceByMailYesNo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CustProfilesOverrideChainProfiles" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="IBAN" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="SwiftCodeNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContactsUpdatedInBizWeb" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateUpdatedContactData" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateUpdatedFinancialData" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FinancialDataUpdatedInBizWeb" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaindataUpdatedInBizWeb" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastUpdatedInBizWeb" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastupdatedFromBizWeb" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateLastFinancialStatement" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AnnualSales" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Result" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NoOfEmployees" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreditBlockAllowOfferAndNewOrders" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="[99x].CustomerSum" Member="CustomerSums">
    <Type Name="CustomerSum">
      <Column Name="Balance" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalOffer" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalLoan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalOrder" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalDiscountPeriod" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalDiscountYear" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalPurchaseValuePeriod" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalPurchaseValueYear" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalSalesAmountPeriod" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalSalesAmountYear" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CustomerNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastMovementDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UtilityBits" Type="System.Data.Linq.Binary" DbType="Binary(6)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="[99x].DebLBalance" Member="DebLBalances">
    <Type Name="DebLBalance">
      <Column Name="CustomerNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Period" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BalanceType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EmployeeNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProjectNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UniqueNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="YearMonth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExchangeAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CurrencyNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VoucherTypeNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UtilityBits" Type="System.Data.Linq.Binary" DbType="Binary(6)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ExtraCostUnitIVNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExtraCostUnitIIINo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExtraCostUnitIINo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExtraCostUnitINo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountryType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="[99x].Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmployeeNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Titel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DepNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InternalTelephone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MobileTelephone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CountryNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PostOffice" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PostCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CommissionNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Telefax" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PrivateTelephone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HireDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ReportsTo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NameReportsTo" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="InActiveYesNo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BankAccount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PostAccount" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="InternalEmailAddress" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="PrivateEmailAddress" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ProjectNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UtilityBits" Type="System.Data.Linq.Binary" DbType="Binary(6)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NickName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BusyReason" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BusyStatus" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EndedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Sex" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Bleeper" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="PersonalWWWAddress" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="UserNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Birthday" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FamilyName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ParentFamilyName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ParentName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastUpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EbusinessType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="PLUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TSApproverEmployeeNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeviationControlYesNo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SubstManagerYesNo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="EmployeeCatNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeCostPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TimeSalesPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="WorkingHours" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AllowTimeSheetRegAllUsers" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="UseWagesortYesNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeWgSrtNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeputyNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaxAttestationAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SuperiorNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BizWebUser" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BizWebPassword" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="[99x].GLAccount" Member="GLAccounts">
    <Type Name="GLAccount">
      <Column Name="GLAccountNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="VATCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TaxClassNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CurrencyNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SingelCurrencyAccountYesNo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ReferenceAkelius" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ColumnAkelius" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InActiveYesNo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MergeToGLAccountNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UtilityBits" Type="System.Data.Linq.Binary" DbType="Binary(6)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="VATReportCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="AccountGroupNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SRUCode2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SRUCode1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepNoSpec" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeeNoSpec" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DebitCredit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DisabledForVoucherEntry" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeeNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccountType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuantitySpec" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="QuantityUnit" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="TransactionInfoSpec" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TransactionInfo" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ProjectNoSpec" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProjectNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InterimTransactionYesNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InterimAccount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductNoSpec" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExtraCostUnit1Spec" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExtraCostUnit2Spec" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExtraCostUnit3Spec" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExtraCostUnit4Spec" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChangedFromVatReportCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="InterimYesNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccountingRuleNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="[99x].GLAccountTransaction" Member="GLAccountTransactions">
    <Type Name="GLAccountTransaction">
      <Column Name="GLAccountNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VoucherDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VoucherNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AccountingYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttestStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BatchNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CorrectedFromUniqueNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountryType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CurrencyNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EmployeeNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExchangeAmount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ExchangeRate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ExtraCostUnitIIINo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExtraCostUnitIINo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExtraCostUnitINo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExtraCostUnitIVNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OldGLAccountNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Period" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PLDocNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProjectNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SLAccount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StatusTransaction" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TaxClassNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UniqueNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UtilityBits" Type="System.Data.Linq.Binary" DbType="Binary(6)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="VATCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VoucherTypeNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WeekNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VATReportCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="VatReportID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EntryDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BankReconciliationRef" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="BankReconciliationStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VoucherChainNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChangeDone" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VoucherSerialNo" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="MainVoucherText" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CustomerNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupplierNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContraEntryChainNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StatusChain" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VoucherID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReferenceType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReferenceId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReferenceRemainderValue" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="[99x].Project" Member="Projects">
    <Type Name="Project">
      <Column Name="ProjectNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StopTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DepNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PMEmployeeNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProjectCategoryNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProjectType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MainProjectNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CostEstimate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IncomeEstimate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MarkupPercent" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="HourEstimate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TransRegAccess" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="IsMainProjectYesNo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="InvoiceableYesNo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ProjectApprovalYesNo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TransferNewYearYesNo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="InActiveYesNo" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="LastUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UtilityBits" Type="System.Data.Linq.Binary" DbType="Binary(6)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="LastUpdatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="InvoiceGroupingMode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OfficeExpensesPercent" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UseInvoicePlanYesNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TransferInvPlanSumsYesNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UseOfficeExpensesYesNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeIncludeExtCommentAsTextLineYesNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TripletexImport" Member="TripletexImports">
    <Type Name="TripletexImport">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProjectNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProjectName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProjectLeader" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DepName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Hours" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SLAProjects" Member="SLAProjects">
    <Type Name="SLAProject">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProjectNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>